pip install flask
pip install googletrans==4.0.0rc1
pip install #
pip install because
pip install earlier
pip install version
pip install has
pip install problem
pip install with
pip install google's
pip install "do
pip install you
pip install accept
pip install cookies"
pip install nltk
pip install stop-words
pip install pymystem3
pip install requests
pip install gensim
pip install openpyxl
pip install scikit-learn
pip install umap-learn
pip install transformers
pip install pandas
pip install hdbscan
pip install langdetect
pip install torchvision